//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueva_DE_SASS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dias_A_Rentar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dias_A_Rentar()
        {
            this.Renta_Usuario_Musica = new HashSet<Renta_Usuario_Musica>();
            this.Renta_Usuario_Videos = new HashSet<Renta_Usuario_Videos>();
            this.Renta_Usuario_Peliculas = new HashSet<Renta_Usuario_Peliculas>();
        }
    
        public int Cod_Dias { get; set; }
        public int Cantidad_D_Dias { get; set; }
        public decimal Precio_por_Dias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Usuario_Musica> Renta_Usuario_Musica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Usuario_Videos> Renta_Usuario_Videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Usuario_Peliculas> Renta_Usuario_Peliculas { get; set; }
    }
}
