//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueva_DE_SASS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Servicio_OnlineEntities : DbContext
    {
        public Servicio_OnlineEntities()
            : base("name=Servicio_OnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dias_A_Rentar> Dias_A_Rentar { get; set; }
        public virtual DbSet<Forma_D_Pago> Forma_D_Pago { get; set; }
        public virtual DbSet<Genero_Vid_Music> Genero_Vid_Music { get; set; }
        public virtual DbSet<GeneroPelicula> GeneroPelicula { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Musica> Musica { get; set; }
        public virtual DbSet<Operaciones> Operaciones { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<Renta_Usuario_Musica> Renta_Usuario_Musica { get; set; }
        public virtual DbSet<Renta_Usuario_Peliculas> Renta_Usuario_Peliculas { get; set; }
        public virtual DbSet<Renta_Usuario_Videos> Renta_Usuario_Videos { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Rol_Operaciones> Rol_Operaciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
    }
}
