//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueva_DE_SASS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Operaciones
    {
        public int Cod_Rol_Operaciones { get; set; }
        public int Cod_Rol { get; set; }
        public int Cod_Operaciones { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
